dist: trusty
language: java
jdk:
  - oraclejdk8
before_script:
  - mvn dependency:resolve-plugins dependency:resolve
script:
  - mvn clean install -Dgpg.skip=true -Pskip-validate
cache:
  directories:
  - $HOME/.m2
